libname ts "C:\Users\bjsul\Documents\NCSU\MSA\Fall\Time-Series\Homework\Homework4";

data ts.pm_v ts.pm_t ts.pm_all;
	set ts.raleigh2_month (rename=Daily_Mean_PM2_5_Concentration=pm2);
	pi=constant("pi");
	t=_n_; *trend var;
	tsq=t**2; *trend squared;
	logt=log(t); *log trend;
	s1=sin(2*pi*1*_n_/12);
	c1=cos(2*pi*1*_n_/12);
	s2=sin(2*pi*2*_n_/12);
	c2=cos(2*pi*2*_n_/12);
	s3=sin(2*pi*3*_n_/12);
	c3=cos(2*pi*3*_n_/12);
	s4=sin(2*pi*4*_n_/12);
	c4=cos(2*pi*4*_n_/12);
	s5=sin(2*pi*5*_n_/12);
	c5=cos(2*pi*5*_n_/12);
	s6=sin(2*pi*6*_n_/12);
	c6=cos(2*pi*6*_n_/12);
	***Seasonal DumDums below***;
	if month(date)=1 then jan=1; else jan=0;
	if month(date)=2 then feb=1; else feb=0;
	if month(date)=3 then mar=1; else mar=0;
	if month(date)=4 then apr=1; else apr=0;
	if month(date)=5 then may=1; else may=0;
	if month(date)=6 then jun=1; else jun=0;
	if month(date)=7 then jul=1; else jul=0;
	if month(date)=8 then aug=1; else aug=0;
	if month(date)=9 then sep=1; else sep=0;
	if month(date)=10 then oct=1; else oct=0;
	if month(date)=11 then nov=1; else nov=0;
	if month(date)=12 then dec=1; else dec=0;
	***Split into training and validation***;
	if _n_ < 55 then output ts.pm_t;
	else output ts.pm_v;
	output ts.pm_all;
run;
